SRA=SRR1972739
REF_ID=AF086833.2
RESULTS_FOLDER=results
RAW_DIR=${RESULTS_FOLDER}/raw
ALIGNED_DIR=${RESULTS_FOLDER}/aligned
VARIANT_DIR=${RESULTS_FOLDER}/variants
ANNOTATED_DIR=${RESULTS_FOLDER}/annotated
QC_DIR=${RESULTS_FOLDER}/qc
SNPEFF_DIR=${RESULTS_FOLDER}/snpEff
SNPEFF_DATA_DIR=${SNPEFF_DIR}/data/reference_db
BUCKET="parul-binf5506"
S3_PREFIX="ebola"

rule create_directories:
    output:
       marker = f"{SNAKEMAKE_DIR}/dirs_created"
    shell:
        mkdir -p $RAW_DIR $ALIGNED_DIR $VARIANT_DIR $ANNOTATED_DIR $QC_DIR $SNPEFF_DATA_DIR

